name: Run E2E Tests
on: workflow_call
jobs:
    e2e:
        # Prevents the workflow running from snapshot updates committed by the bot
        if: github.actor != 'github-actions[bot]'
        runs-on: ubuntu-latest
        steps:
          # Checkout the PR branch
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
              ref: ${{ github.head_ref }}
              fetch-depth: 0
    
          # Set up Node
          - name: Set up Node
            uses: actions/setup-node@v4
            with:
              node-version: '20.x'
              registry-url: 'https://registry.npmjs.org'
              scope: '@aws'

          # Set up Docker Buildx
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            
          # Cache Docker layers
          - name: Cache Docker layers
            uses: actions/cache@v3
            with:
              path: /tmp/.buildx-cache
              key: ${{ runner.os }}-buildx-${{ hashFiles('**/package-lock.json', '**/ui-tests/package-lock.json', 'Dockerfile') }}
              restore-keys: |
                ${{ runner.os }}-buildx-

          # Build Docker image with caching
          - name: Build E2E tests Docker Image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: false
              load: true
              tags: flarechatui-e2e-image:latest
              cache-from: type=local,src=/tmp/.buildx-cache
              cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

          # Move cache to prevent unlimited growth
          - name: Move cache
            run: |
              rm -rf /tmp/.buildx-cache
              mv /tmp/.buildx-cache-new /tmp/.buildx-cache

          # Run the Docker container
          - name: Run E2E tests Docker Container
            run: npm run docker:run
    
          # Extract test results from Docker container
          - name: Extract test results from Docker container
            if: ${{ !failure() }}
            run: npm run docker:inspect:override
              
          # Upload an artifact of all the results
          - name: Upload E2E results
            uses: actions/upload-artifact@v4
            if: always()
            with:
              name: snapshots
              path: ./ui-tests/__results__
              retention-days: 30
    
          # Your commented out snapshot replacement section preserved
          # - name: Replace Snapshots in PR Branch
          #   if: ${{ !failure() }}
          #   run: |
          #     git config user.name "github-actions[bot]"
          #     git config user.email "github-actions[bot]@users.noreply.github.com"
          #     git fetch origin
          #     git checkout ${{ github.head_ref }}
          #     git add ./ui-tests/__results__/__snapshots__
          #     git diff --staged --quiet || git commit -m "[Docker] Update E2E image snapshots"
          #     git push origin ${{ github.head_ref }}
          #   env:
          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    report:
      needs: e2e
      if: always()
      uses: ./.github/workflows/test_report.yml
