name: Run Chromium E2E Tests
on: workflow_call
jobs:
    e2e-chromium:
        runs-on: ubuntu-latest
        steps:
          # Checkout the PR branch
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
              ref: ${{ github.head_ref }}
              fetch-depth: 0
              
          # Download the Docker image
          - name: Download Docker image
            uses: actions/download-artifact@v4
            with:
              name: docker-image
              
          # Load the Docker image
          - name: Load Docker image
            run: docker load < mynah-ui-e2e.tar
            
          # Run Chromium tests
          - name: Run Chromium E2E tests
            run: npm run docker:run:chromium
            
          # Extract test results
          - name: Extract test results
            if: always()
            run: npm run docker:extract
              
          # Upload results
          - name: Upload Chromium results
            uses: actions/upload-artifact@v4
            if: always()
            with:
              name: test-results-chromium
              path: ./ui-tests/__results__
              retention-days: 30
