name: New PR created
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
jobs:
  notify:
    if: github.event.pull_request.draft == false
    name: Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Post message
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "title": ${{ toJson(github.event.pull_request.title) }},
              "author": ${{ toJson(github.event.pull_request.user.login) }},
              "link": ${{ toJson(github.event.pull_request.html_url) }},
              "repository": "FlareChatUI" 
            }
  lint:
    uses: ./.github/workflows/lint.yml
  e2e-linux:
    uses: ./.github/workflows/e2e-linux.yml