name: Check Lint, Tests and Build
on:
  pull_request:
    branches: [main, feature/*, fix/*]
    types: [opened, reopened, ready_for_review, synchronize]
jobs:
  notify:
    if: github.event.pull_request.draft == false
    name: Slack notification
    runs-on: [ubuntu-latest]
    steps:
      - name: Post message
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "title": ${{ toJson(github.event.pull_request.title) }},
              "author": ${{ toJson(github.event.pull_request.user.login) }},
              "link": ${{ toJson(github.event.pull_request.html_url) }},
            }
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 20
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@aws'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Unit tests
        run: npm run tests:unit
      - name: Run Lint
        run: npm run lint